namespace: devopsarr
name: sonarr
# Version will be updated by workflow
version: 0.0.1
readme: README.md
authors:
  - Fuochi (github.com/Fuochi)
description: "Ansible collection for Sonarr"
license_file: LICENSE
tags:
  - sonarr
  - arr
  - series
repository: https://github.com/devopsarr/ansible-collection-sonarr
#documentation: https://github.com/ansible-collection-migration/devopsarr.sonarr/tree/main/docs
homepage: https://github.com/devopsarr/ansible-collection-sonarr
issues: https://github.com/devopsarr/ansible-collection-sonarr/issues
build_ignore:
  - .gitignore
  - .github/
  - changelogs/.plugin-cache.yaml