namespace: devopsarr
name: sonarr
version: 1.1.1 # x-release-please-version
readme: README.md
authors:
  - Fuochi (github.com/Fuochi)
description: "Ansible collection for Sonarr"
license_file: LICENSE
tags:
  - sonarr
  - arr
  - series
repository: https://github.com/devopsarr/ansible-collection-sonarr
documentation: https://devopsarr.github.io/ansible-doc/collections/devopsarr/sonarr/
homepage: https://github.com/devopsarr/ansible-collection-sonarr
issues: https://github.com/devopsarr/ansible-collection-sonarr/issues
build_ignore:
  - .gitignore
  - .github/
  - changelogs/.plugin-cache.yaml