name: CI
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main

jobs:
  ci:
    uses: devopsarr/shared-workflows/.github/workflows/ansible_collection_ci.yml@main
    with:
      namespace: "devopsarr"
      collection-name: "sonarr"
    secrets: inherit
  doc-lint:
    uses: devopsarr/shared-workflows/.github/workflows/ansible_doc_lint.yml@main