# Ansible Module release workflow.
name: Release Management

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    branches:
      - main

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
#permissions:
#  contents: write

# Default values to simplify job configurations below.
env:
  # Python language version to use This value should also be updated
  # in the testing workflow if changed.
  PYTHON_VERSION: '3.10'

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
        with:
          # Allow relase please to access older tag information.
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Release Please
        id: release_please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          token: ${{ secrets.GITHUB_TOKEN }}